name: Release

on:
  push:
    branches:
      - master
      - main

jobs:
  release:
    uses: finsweet/workflow-release/.github/workflows/release.yml@main
    secrets: inherit # Remove the nested structure and just use inherit
